name: ci

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"

      - uses: pnpm/action-setup@v4

      - id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: node-modules-${{ runner.os }}-${{ hashFiles('.tool-versions') }}-${{ hashFiles('pnpm-lock.yaml') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - run: pnpm t
